apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mcshortlink.fullname" . }}-redis-pvc
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  selector:
    matchLabels:
      data: redis
