version: "3"
services:
  mcshort:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis
    ports:
    - "127.0.0.1:8000:8000"
  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "redisdata:/data"

volumes:
  redisdata:
