name = "mcshortlink-worker"
account_id = "cc9551da1de1b07834198a21b965d463"
workers_dev = true
main = "index.js"
compatibility_date = "2024-01-29"
kv_namespaces = [
    { binding = "MCSHORT_LINK_KV", id = "14d4c6d7cc734c319c8deddc6b1e5dbb" }
]